### ISSUE TITLE
install cublas facing problem No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by JamesBVMNetwork** [replicate/cog-flux#30]
How can I install cublas to use, command inside cog.yaml
```
run: 
- pip install git+https://github.com/aredden/torch-cublas-hgemm.git@master
```

**Comment by lucataco** [comment]
In float8_quantize.py it tries to import but handles the case when its not available.
Code still functions without it, its an optional optimization that can provide performance improvements on consumer GPUs with float16 precision, but isn't required for core functionality.
