### ISSUE TITLE
output type is different in local and server

### ISSUE THREAD

**Issue by robinshins** [replicate/cog-flux#37]
I got https url in local environment.
But if I run this api on server, output type is replicate.helper.FileOutput

**Comment by nitinmukesh** [comment]
@robinshins 

Any tips on how to run locally, plz.

**Comment by robinshins** [comment]
> @robinshins
> 
> Any tips on how to run locally, plz.

Ah what i mean is run it in localhost

**Comment by lucataco** [comment]
See our docs for FileOuput here: [https://replicate.com/docs/topics/predictions/output-files#fileoutput-objects](https://replicate.com/docs/topics/predictions/output-files#fileoutput-objects)
