### ISSUE TITLE
Problem with loras

### ISSUE THREAD

**Issue by micos7** [replicate/cog-flux#54]
On this model (black-forest-labs/flux-dev-lora) I uses this lora trained on anime images:

https://pub-2f822541d6c848da96e739a2d9e75540.r2.dev/72e6dfee1e1f4220b3845cbafae3fd7d_pytorch_lora_weights.safetensors

trigger word:  ANIMESTYLE

I get: `Prediction failed.
'transformer.single_transformer_blocks.0.proj_mlp.lora_A.weight'`

Thanks for your time.

Edit:
 Using the model resulting from this training: `https://replicate.com/ostris/flux-dev-lora-trainer/train` with the same lora it was working a couple of days back.

**Comment by lucataco** [comment]
Our flux lora trainer saves files as lora.safetensors by default, are you sure you trained that LoRA on Replicate?
If so, kindly share the training run and its configurations so that we can take a deeper look at how you trained it

**Comment by micos7** [comment]
i used this https://fal.ai/models/fal-ai/flux-lora-fast-training with isStyle flag. I know its not replicate ,but the exact same lora was working a few days back, might be related to same recent changes? Thanks.

**Comment by micos7** [comment]
I used this one if it is helpful https://fal.ai/models/fal-ai/flux-lora-fast-training

**Comment by lucataco** [comment]
Fixed with [PR#60](https://github.com/replicate/cog-flux/pull/60/files)

**Comment by micos7** [comment]
Thanks for the heads up. Any chance this fix will appear on the models generated by  https://github.com/replicate/flux-fine-tuner ?
